#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^6'
bspc rule -a mailspring desktop='^6'
bspc rule -a Steam desktop='^9'
bspc rule -a elisa desktop='^10'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a "Blender Render" state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#bf616a"
bspc config normal_border_color         "#4c566a"
bspc config active_border_color         "#4c566a"

#
# Autostart
#
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Picom
picom -CGb --experimental-backends &
# Network Applet
# nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
#Apps
# discord &
# mailspring &
