add_newline = false 
format = "$all$directory$git_branch$git_commit$git_state$git_metrics$git_status$character"
[package]
symbol = " "

[nodejs]
symbol = " "

[python]
symbol = " "

[lua]
symbol= " "

[git_branch]
symbol= " "

[cmake]
symbol = "卑 "

[golang]
symbol = "ﳑ "

